CC = gcc
CFLAGS = -Wall -Wextra -Werror -std=c11

all:
	make state_sort state_search

state_sort:
	$(CC) $(FLAGS) state_sort.c binary_files_operations.c date_struct.c -o ./../build/Quest_1

state_search:
	$(CC) $(FLAGS) state_search.c date_struct.c binary_files_operations.c -o ./../build/Quest_2